### ISSUE TITLE
Docker buliding wrong tag

### ISSUE THREAD

**Issue by marrts** [tesseract-robotics/tesseract_qt#103]
The docker is setup to build based off the tag, supposedly for allowing tagged versions and a master branch, but this repo has "main" instead of master, so it is looking for tesseract_planning:{OS}-main which doesn't exist: https://github.com/tesseract-robotics/tesseract_qt/actions/runs/8057216475/job/22007861668#step:5:180

**Comment by Levi-Armstrong** [comment]
Fixed by #104

**Comment by Levi-Armstrong** [comment]
I believe this is fixed now with latest changes to branch name and CI scripts
