### ISSUE TITLE
Build issue on Noble/Jazzy

### ISSUE THREAD

**Issue by rjoomen** [tesseract-robotics/tesseract_qt#111]
I tried building Tesseract on Ubuntu 24.04 (Noble) with ROS2 Jazzy and ran (after fixing some minor other issues) into this issue, related to `qt5_wrap_cpp`, and I have no idea how to fix it:

```
Starting >>> tesseract_qt
--- stderr: tesseract_qt
/bin/sh: 1: @/home/roelof/tesseract_ws/build/tesseract_qt/common/include/tesseract_qt/common/moc_environment_wrapper.cpp_parameters: not found
gmake[2]: *** [common/CMakeFiles/tesseract_qt_common.dir/build.make:78: common/include/tesseract_qt/common/moc_environment_wrapper.cpp] Error 127
gmake[2]: *** Waiting for unfinished jobs....
/bin/sh: 1: @/home/roelof/tesseract_ws/build/tesseract_qt/common/include/tesseract_qt/common/moc_environment_manager.cpp_parameters: not found
gmake[2]: *** [common/CMakeFiles/tesseract_qt_common.dir/build.make:74: common/include/tesseract_qt/common/moc_environment_manager.cpp] Error 127
/bin/sh: 1: @/home/roelof/tesseract_ws/build/tesseract_qt/common/include/tesseract_qt/common/models/moc_component_info_manager_model.cpp_parameters: not found
gmake[2]: *** [common/CMakeFiles/tesseract_qt_common.dir/build.make:90: common/include/tesseract_qt/common/models/moc_component_info_manager_model.cpp] Error 127
/bin/sh: 1: @/home/roelof/tesseract_ws/build/tesseract_qt/common/include/tesseract_qt/common/models/moc_json_model.cpp_parameters: not found
gmake[2]: *** [common/CMakeFiles/tesseract_qt_common.dir/build.make:82: common/include/tesseract_qt/common/models/moc_json_model.cpp] Error 127
/bin/sh: 1: @/home/roelof/tesseract_ws/build/tesseract_qt/common/include/tesseract_qt/common/models/moc_yaml_model.cpp_parameters: not found
gmake[2]: *** [common/CMakeFiles/tesseract_qt_common.dir/build.make:86: common/include/tesseract_qt/common/models/moc_yaml_model.cpp] Error 127
/bin/sh: 1: -o: not found
gmake[2]: *** [common/CMakeFiles/tesseract_qt_common.dir/build.make:166: common/ui_load_environment_widget.h] Error 127
gmake[1]: *** [CMakeFiles/Makefile2:556: common/CMakeFiles/tesseract_qt_common.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:136: all] Error 2
---
Failed   <<< tesseract_qt [1.43s, exited with code 2]
```

@Levi-Armstrong, do you have an idea?

**Comment by Levi-Armstrong** [comment]
Do you have a branch to look at?

**Comment by rjoomen** [comment]
No branch, just `master`.

Only fix needed is adding `C` to the languages here `project(${pkg_extracted_name} VERSION ${pkg_extracted_version} LANGUAGES C CXX)` in some of the makefiles, because of an issue with a dependency (issue seems related to [this](https://gitlab.kitware.com/vtk/vtk/-/issues/18552)).

**Comment by rjoomen** [comment]
For reference, a workaround like [this](https://bitbucket.org/icldistcomp/parsec/pull-requests/508/parsecconfig-ensures-that-c-enabled-when) might be needed for the `MPI::MPI_C` target issue requiring the C language to be enabled. But I don't think that's related to the QT issue.

**Comment by rjoomen** [comment]
Related: https://github.com/tesseract-robotics/tesseract_ros2/issues/86

**Comment by Levi-Armstrong** [comment]
What are the next steps on fixing this?

**Comment by rjoomen** [comment]
Just today I got it all building. 

- Having to add C to the languages seems to be inevitable. Issue is tesseract_urdf depends on PCL, which in turn depends on VTK, which in turn depends on MPI, which is the cause of the MPI::MPI_C include problem needing the C language.
- I solved the QT issues by switching some of the makefiles to using AUTOMOC, AUTOUIC and AUTORCC. Strange thing is that not all makefiles needed this, sometimes qt5_wrap_cpp and qt5_wrap_ui work fine. It seems some kind of path issue, maybe you can find out what causes this.

I'll submit a PR to `tesseract_qt` tomorrow for you to check out and we can discuss how to continue.

**Comment by rjoomen** [comment]
Submitted. The mixing of AUTOMOC/UIC/RCC and qt5_wrap_* is not ideal, of course, either we find out why qt5_wrap_* fails, or switch everything over to AUTO*.
