### ISSUE TITLE
adsTargets.cmake does not exist after building Qt-Advanced-Docking-System 

### ISSUE THREAD

**Issue by savolla** [tesseract-robotics/tesseract_qt#4]
Hi, I'm trying to build **tesseract_ros** which includes **tesseract_qt** as a dependency. However I'm getting the following error while bulding with `catkin build`. It asks for `adsTargets.cmake` which is not present in devel directory. I tried to follow the solution in [this](https://github.com/tesseract-robotics/tesseract_qt/issues/1) issue but I think this author has a different setup than mine. 

```bash
CMake Error at /home/savolla/tesseract_ws/src/Qt-Advanced-Docking-System/src/qtadvanceddockingConfig.cmake:2 (include):
  include could not find load file:

    /home/savolla/tesseract_ws/src/Qt-Advanced-Docking-System/src/adsTargets.cmake
Call Stack (most recent call first):
  plot/CMakeLists.txt:11 (find_package)
```

**Comment by Levi-Armstrong** [comment]
I recommend installing using `ros-noetic-qt-advanced-docking`

**Comment by savolla** [comment]
This solved my issue. I successfully built the package. I think this is a critical info and could be included in the installation section of readme. Thank you!
