### ISSUE TITLE
ERROR: tesseract_qt: Cannot locate rosdep definition for [gz-math7] when installing dependencies using rosdep on Ubuntu 20.04

### ISSUE THREAD

**Issue by alpharomeo911** [tesseract-robotics/tesseract_qt#45]
Hello,

I'm trying to build tesseract by following the documentation on ROS Noetic from this website -- https://tesseract-docs.readthedocs.io/en/latest/_source/intro/getting_started_doc.html and I keep getting this dependency issue.

Further to get tesseract building, I had to clone tesseract_ext and opw_kinematics in the directory of the workspace.

The only error I'm getting for a while is when tesseract_qt is building:
```
Errors     << tesseract_qt:cmake /home/hsrbtower/tesseract_ws/logs/tesseract_qt/build.cmake.000.log                                                                                                       
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Graphviz (missing: graphviz_cdt_FOUND graphviz_cgraph_FOUND
  graphviz_gvc_FOUND graphviz_gvpr_FOUND graphviz_lab_gamut_FOUND
  graphviz_pathplan_FOUND graphviz_xdot_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGraphviz.cmake:50 (find_package_handle_standard_args)
  common/CMakeLists.txt:4 (find_package)

```

System is Ubuntu 20.04, ROS distro is Noetic, if any other system info is needed, let me know.

**Comment by Levi-Armstrong** [comment]
Run .add-gazebo-ppa script using sudo to add the gazebo ppa and install depends.

**Comment by alpharomeo911** [comment]
Thanks, this solves the issue! Keep up the great work!

**Comment by decdox** [comment]
HI, I ran into the same issue when updating the latest version of Tesseract, can you shar e the gazebo ppa you used? Thank you.

**Comment by alpharomeo911** [comment]
Hi @decdox did you execute this script as `sudo` https://github.com/tesseract-robotics/tesseract_qt/blob/main/.add-gazebo-ppa?
This should add the gazebo ppa and install the dependencies.

**Comment by decdox** [comment]
> Author

@alpharomeo911 HI, still not. After running the `.add-gazebo-ppa` script, then I run 
```
rosdep install -y --from-paths ~/tesseract_ws/src --ignore-src --rosdistro noetic
```
mentioned in the [gettting started](https://tesseract-docs.readthedocs.io/en/latest/_source/intro/getting_started_doc.html), error still appears:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
tesseract_qt: Cannot locate rosdep definition for [gz-math7]
```
If i ignore this error and build, the catkin errors are different from yours:
```
CMake Error at /home/zing/mealAssistiveRobot/tesseract_ws/src/tesseract_qt/rendering/CMakeLists.txt:10 (find_package):
  By not providing "Findgz-rendering7.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "gz-rendering7", but CMake did not find one.

  Could not find a package configuration file provided by "gz-rendering7"
  with any of the following names:

    gz-rendering7Config.cmake
    gz-rendering7-config.cmake

  Add the installation prefix of "gz-rendering7" to CMAKE_PREFIX_PATH or set
  "gz-rendering7_DIR" to a directory containing one of the above files.  If
  "gz-rendering7" provides a separate development package or SDK, be sure it
  has been installed.
```
Thank you anyway, I am going to try the installation again.

**Comment by Levi-Armstrong** [comment]
We are using the latest version of gazebo libraries which have not made it into rosdep yet so you have to manually install them.
`sudo apt install libgz-rendering7-dev`

**Comment by alpharomeo911** [comment]
> 
Here's the output
```
libgz-math7-dbg/unknown 7.1.0-1~focal amd64
libgz-math7-dev/unknown,now 7.1.0-1~focal amd64 [installed,automatic]
libgz-math7-eigen3-dev/unknown,now 7.1.0-1~focal amd64 [installed,automatic]
libgz-math7/unknown,now 7.1.0-1~focal amd64 [installed,automatic]
python3-gz-math7/unknown 7.1.0-1~focal amd64
ruby-gz-math7/unknown 7.1.0-1~focal amd64
```

Also @decdox try the new solution posted by @Levi-Armstrong here - https://github.com/tesseract-robotics/tesseract_qt/issues/45#issuecomment-1562959502

**Comment by decdox** [comment]
@Levi-Armstrong @alpharomeo911 Thank you, my issue is solved. I also found some instruction in [focalbuild.yml](https://github.com/tesseract-robotics/tesseract_qt/blob/d81b5aa3b5cac4c00dd718c71be088fea4c007a7/.github/workflows/focal_build.yml#L26-L27):
```
      ROSDEP_SKIP_KEYS: "bullet bullet-extras fcl iwyu gz-rendering7 gz-common5 gz-math7"
      ADDITIONAL_DEBS: "libgz-rendering7-dev libgz-common5-dev libgz-math7-dev"
```
If you add a `--skip-keys` while using `rosdep install`, the dependencies are met:
```
rosdep install --from-paths src --ignore-src -r -y --skip-keys="bullet bullet-extras fcl iwyu gz-rendering7 gz-common5 gz-math7"
```
You need to install the three packages `libgz-rendering7-dev libgz-common5-dev libgz-math7-dev` maually using `apt install <package> after running this [script](https://github.com/tesseract-robotics/tesseract_qt/blob/main/.add-gazebo-ppa) for updating gazebo version.
