### ISSUE TITLE
QApplication::sendEvent calls

### ISSUE THREAD

**Issue by rjoomen** [tesseract-robotics/tesseract_qt#81]
I believe QApplication::sendEvent is called wrongly. The [documentation states](https://doc.qt.io/qt-6/qcoreapplication.html#sendEvent) "The event is not deleted when the event has been sent.". Therefore, calling sendEvent with an event created through [a non-owning new call ](https://github.com/tesseract-robotics/tesseract_qt/blob/main/common/src/environment_wrapper.cpp#L147) seems incorrect to me.

**Comment by Levi-Armstrong** [comment]
Fixed and a new release 0.20.2 has been generated. Thank you for reporting.
